### PR TITLE
Add additional container image with fully configured example IOC

### PR DESCRIPTION
**Pull request by GDYendell**

### CODE REVIEW

**Comment by GDYendell** [comment]
This works except I can't read the PVI V4 PV (I can read the PVA plugin's V4 PV). Do I need do something for the PV to be created?

**Review by gilesknap — APPROVED** [review]
Looks Good.

Will merge this as is and then investigate PVI.

**Comment by gilesknap** [comment]
@GDYendell FYI. The following works perfectly. It's the new gold standard for demoing epics-containers:

```bash
podman run --name demo --net host -dit --rm -v/tmp/opi:/epics/opi ghcr.io/epics-containers/ioc-adsimdetector-demo:2024.7.1
phoebus.sh -resource /tmp/opi/index.bob
# use phoebus to start the detector and enable PVA plugin.
c2dv --pv BL01T-EA-TST-02:PVA:OUTPUT &
```

TODO: maybe we could insert dbpf commands into IOC.yaml so that the camera and PVA are started on launch.
But maybe - seeing the GUI and starting things is a better demo anyway.

**Comment by gilesknap** [comment]
@GDYendell 

I say gold standard. But ...

I just did
```
podman stop demo
```
and my PVs are still there - probably because you are running it?
Use of `net host` in a shared environment is maybe not a great idea, particularly when demo IOCs have fixed PVs.

Just having a play with some options here and will get back to you ...

**Comment by gilesknap** [comment]
OK what I wanted to do was use
```
podman run --net podman
```
and then do the same for the phoebus container.

But this fails because X11 forwarding does not like the podman network. 

For docker this would just work great but podman networking is another story that can really only be solved by launching a gateway.

Therefore, the simpler solution would be to provide another environment variable and use that to set `P` in the ioc.yaml. We could provide a default for that in the Dockerfile, but encourage users to make a unique one.

Benefits are:
- works for docker and podman
- simple and requires no extra containers 
- phoebus can be run directly on the host

**Comment by GDYendell** [comment]
So, the FastCS IOC container entrypoint requires passing the PV prefix you want to use. Maybe this could do the same? Of course this doesn't guarantee devs will use unique names, but it could be in the instructions that they should.

**Pull request merged**
